
# POST https://daitl.000webhostapp.com/index.php HTTP/1.1
# Content-Type: application/json
# {
#     "DATA":"Hello1231231"
# }
POST http://httpbin.org/anything HTTP/1.1
content-type: text/plain

Test123123213

