
# POST https://daitl.000webhostapp.com/index.php HTTP/1.1
# Content-Type: application/json
# {
#     "DATA":"Hello1231231"
# }
POST https://daitl.000webhostapp.com/index.php HTTP/1.1
content-type: application/x-www-form-urlencoded

DATA=Test123123213
